image: golang:1.21

stages:
#  - check
  - build

#syntaxcheck:
#  stage: check
#  script:
#    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
#    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
#    - cd $GOPATH/src/$REPO_NAME
#    - go fmt
#    - go vet
#    - go lint

Windows build:
  stage: build
  script:
    - go get -d -v
    - GOOS=windows GOARCH=amd64 go build -o windows/amd64/protoc-gen-php8.exe
    - GOOS=windows GOARCH=arm go build -o windows/arm/protoc-gen-php8.exe
  only:
    - master

Linux build:
  stage: build
  script:
    - go get -d -v
    - GOOS=linux GOARCH=amd64 go build -o linux/amd64/protoc-gen-php8
    - GOOS=linux GOARCH=arm go build -o linux/arm/protoc-gen-php8
  only:
    - master

MacOS build:
  stage: build
  script:
    - go get -d -v
    - GOOS=darwin GOARCH=amd64 go build -o macos/amd64/protoc-gen-php8
    - GOOS=darwin GOARCH=arm go build -o macos/arm/protoc-gen-php8
  only:
    - master
